news_authenticity/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('news_feed.urls')),
    path('', include('users.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

news_feed/urls.py
from django.urls import path
from news_feed.views import (
    HomePageView,
    NewsFeedListing,
    ChangeVoteCount
)

app_name = "news"

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('news', NewsFeedListing.as_view(), name='news-list'),
    path('change_vote_count', ChangeVoteCount.as_view(), name='change-vote-count'),
]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from users.views import (
    LoginView,
    SignUpView,
)

app_name = "users"

urlpatterns = [
    path('login', LoginView.as_view(), name='login'),
    path('signup', SignUpView.as_view(), name='sign-up'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

commons/models.py
from django.db import models


class TimestampModel(models.Model):
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True, null=True)

    class Meta:
        abstract = True

news_feed/models.py
from django.db import models
from django.core.validators import URLValidator
from commons.models import TimestampModel
# Create your models here.


class Category(TimestampModel):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return str(self.name)


class NewsSource(TimestampModel):
    url = models.TextField(validators=[URLValidator()])

    headers = models.JSONField(null=True, blank=True)
    params = models.JSONField(null=True, blank=True)

    def __str__(self):
        return str(self.url)


class NewsData(TimestampModel):
    url = models.TextField(validators=[URLValidator()], unique=True)
    title = models.TextField()
    content = models.TextField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    positive_votes = models.BigIntegerField(default=0)
    negative_votes = models.BigIntegerField(default=0)

    def __str__(self):
        return str(self.url)

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from commons.models import TimestampModel
from news_feed.models import Category
# Create your models here.


class User(AbstractUser, TimestampModel):
    preferences = models.ManyToManyField(Category, blank=True, null=True)

    def __str__(self):
        return str(self.username)

users/forms.py
from users.models import User
from django.contrib.auth.forms import UserCreationForm


class SignUpForm(UserCreationForm):

    class Meta(UserCreationForm):
        model = User
        fields = ("username", "first_name", "last_name", "password1", "password2", "email", "preferences")

    def save(self, commit=True):
        user = UserCreationForm.save(self, commit)
        preferences = self.cleaned_data.get("preferences")
        user.preferences.add(*preferences)
        return user

news_feed/views.py
import json
import logging
from http import HTTPStatus
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from django.http import JsonResponse, HttpResponseRedirect
from django.views.generic import ListView
from news_feed.models import NewsData

# Create your views here.
logger = logging.getLogger("news_authenticity")


class HomePageView(View):

    def get(self, request):
        """
        Redirecting end user to news page
        """
        return HttpResponseRedirect("/news")


class NewsFeedListing(ListView):

    def get_queryset(self):
        """
        If a user is logged in then he is shown news based on the preferences but if he has not logged in than 
        news belonging to all the categories are shown to him.
        """
        user = self.request.user
        if user.is_authenticated:
            queryset = NewsData.objects.filter(category__in=user.preferences.values_list("id", flat=True))
        else:
            queryset = NewsData.objects.all()
        return queryset

    template_name = "news_feed/news_list.html"
    model = NewsData
    paginate_by = 10
    context_object_name = 'news_list'
    ordering = '-positive_votes'


class ChangeVoteCount(LoginRequiredMixin, View):
    """
    If a user is logged in then only user can change the vote
    """

    def put(self, request):
        try:
            """
            A logged in user can either upvote or downvote the news
            """
            data = json.loads(request.body)
            vote_type = str(data.get('voteType'))
            news_id = data.get('newsId')
            if vote_type and news_id:
                news_obj = NewsData.objects.filter(pk=news_id).first()
                if int(vote_type) == 0:
                    news_obj.negative_votes += 1
                elif int(vote_type) == 1:
                    news_obj.positive_votes += 1
                news_obj.save()
                resp = {'success': 'vote done.'}
                logger.info(
                    dict(
                        message="Vote done",
                        class_name="ChangeVoteCount",
                        method_name="post",
                    )
                )
            return JsonResponse(resp, status=HTTPStatus.OK)
        except Exception as e:
            logger.error(
                dict(
                    message="'Exception in change vote'",
                    class_name="ChangeVoteCount",
                    method_name="post",
                    errors=e,
                )
            )
            return JsonResponse({"message": "failed"}, status=HTTPStatus.INTERNAL_SERVER_ERROR)

users/views.py
import logging
from django.shortcuts import render
from django.views import View
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect

from users.forms import SignUpForm

logger = logging.getLogger("news_authenticity")


class LoginView(View):

    def get(self, request):
        """
        Displaying the form for authentication through which user can login
        """
        form = AuthenticationForm()
        return render(request, "users/login.html", context={"form": form})

    def post(self, request):
        """
        Authenticating user and allow him to login inside the system
        """
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.data.get("username")
            password = form.data.get("password")
            user = authenticate(username=username, password=password)

            if user and user.is_active:
                login(request, user)
                return HttpResponseRedirect("/news")

        else:
            return render(request, "users/login.html", context={"form": form})


class SignUpView(View):
    def get(self, request):
        """
        Displaying the signup form so that news user can enter into the system
        """
        form = SignUpForm()
        return render(request, 'users/signup.html', {'form': form})

    def post(self, request):
        """
        Getting new user data so that he can be registered into the system
        """
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect("/news")
        return render(request, 'users/signup.html', {'form': form})

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <script src="{% static 'css/news.css' %}"></script>
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="nav navbar-header navbar-brand">
      <a class="active" href="{% url 'news:news-list' %}">NewsFeed</a>
    </div>
    <ul class="nav navbar-nav">
      {% if user.is_authenticated %}
        <li class="nav navbar-brand navbar-left">Hello {{request.user.username}}</li>
        <li class="nav navbar-left"><a href="{% url 'users:logout' %}">Logout</a></li>
      {% else %}
        <li class="nav login"><a href="{% url 'users:login' %}">Login</a></li>
        <li class="nav login"><a href="{% url 'users:sign-up' %}">Signup</a></li>
      {% endif %}
    </ul>
  </div>
</nav>

<div class="container">
<!--  <h3>Latest News</h3>-->

  {% block container %}
  {% endblock %}

</div>
{% block javascript %}
{% endblock %}
<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'js/infinite.min.js' %}"></script>
</body>
</html>

templates/news_feed/email_template.html
<html>
    <head>
        <title>
            Fetched Relevant news according to {{category}}
        </title>
    </head>
    <body>
        <h1>Hi, {{username}}</h1>
        <div class="row">
            <p>
                As per your preference in {{category}}, we found relevant news for you.
            </p>
        </div>
        <div class="row">
            <a href="{{url}}" >Click here.</a>
        </div>
    </body>
</html>

templates/news_feed/news_list.html
{% extends 'base.html' %}
{% load static %}

{% block container %}
{% csrf_token %}
<div class="container">
    <div class="row">
        <div class="col-lg-12 offset-lg-2">
            <div class="infinite-container">
                {% if not user.is_authenticated %}
                    <h4 style="color:red">Please Login in order to upvote and downvote the article</h4>
                {% endif %}
                {% for news in news_list %}
                <div class="infinite-item">
                    <div class="col-sm-12">

                        <h3>
                            <a href="{{news.url}}" target="_blank" style="color: blue;">{{news.title}}</a>
                        </h3>
                        <div class="col-sm-9">
                            <p>{{news.content}}</p>
                            <a href="{{news.url}}" target="_blank">Read more</a>
                        </div>
                        <div class="col-sm-3">
                            {% if user.is_authenticated %}
                                <button class="btn btn-primary" onclick="changeVoteCount(1, {{news.id}}, '{% url 'news:change-vote-count' %}')" {% if not user.is_authenticated %} diabled {% endif %}>Vote up</button>
                                <button class="btn btn-warning" style="color:black"
                                    onclick="changeVoteCount(0, {{news.id}}, '{% url 'news:change-vote-count' %}')">Vote down</button>
                            {% endif %}
                        </div>
                    </div>
                    {% endfor %}
                </div>
                <div class="col-sm-6" style="margin-top: 20px;margin-bottom: 20px;">
                    {% if page_obj.has_previous %}
                    <a class="infinite-more-link btn btn-primary"
                        href="?page={{ page_obj.previous_page_number }}">Previous page</a>
                    {% endif %}

                    {% if page_obj.has_next %}
                    <a class="infinite-more-link btn btn-primary" href="?page={{ page_obj.next_page_number }}">More</a>
                    {% endif %}
                </div>
            </>
        </div>
    </div>
</div>

{% endblock %}

{% block javascript %}
<script src="{% static 'js/changeVote.js' %}"></script>
{% endblock %}

templates/users/login.html
{% extends 'base.html' %}

{% block container %}
<form method="post">
    {% csrf_token %}
    {{ form.non_field_errors }}
    <div class="form-group">

        <label for="{{ form.username.id_for_label }}">Username:</label>
        {{ form.username }}
        {{ form.username.errors }}

    </div>
    <div class="form-group">

        <label for="{{ form.password.id_for_label }}">Password:</label>
        {{ form.password }}
        {{ form.password.errors }}
    </div>
    <button type="submit">Login</button>
</form>
{% endblock %}
{% block javascript %}

{% endblock %}

templates/users/signup.html
{% extends 'base.html' %}

{% block container %}
<form method="post" id='signup'  novalidate>
    {% csrf_token %}
    {% for field in form %}
      <table border=0>
        <tr>
      <td style='width:100px;color:black'>{{ field.label_tag }}</td>
      <td>{{ field }}</td>
        </tr>
        {% for error in field.errors %}
          <p> style="color: red">{{ error }}</p>
        {% endfor %}

    {% endfor %}
  <tr><td><button type="submit">Sign up</button></td></tr>

  </table >
  </form>
{% endblock %}
{% block javascript %}

{% endblock %}